#Container image that runes your code
FROM alpine: 3.10

#Copies your code file from your action repository to the filesystm
COPY entrypoint.sh /entrypoint.sh

#Code file to execute when the docker container starts up
ENTRYPOINT["/entrypoint.sh"]